### ISSUE TITLE
AttributeError: 'CountryField' object has no attribute 'db_collation'

### ISSUE THREAD

**Issue by njNafir** [SmileyChris/django-countries#354]
Hello 
Working with django-countries, in django version 3.2 it's getting an error, 

> `Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 150, in handle
    ProjectState.from_apps(apps),
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/db/migrations/state.py", line 220, in from_apps
    model_state = ModelState.from_model(model)
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/db/migrations/state.py", line 407, in from_model
    fields.append((name, field.clone()))
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 512, in clone
    name, path, args, kwargs = self.deconstruct()
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django_countries/fields.py", line 352, in deconstruct
    name, path, args, kwargs = super().deconstruct()
  File "/home/njn/anaconda3/envs/skytrip/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1089, in deconstruct
    if self.db_collation:
AttributeError: 'CountryField' object has no attribute 'db_collation'`

Hopefully, django-countries is not ready for django 3.2 yet
can you add self.db_collation = False in fields.py in the init of class CountryField?

Using django version 3.2.4 and django-countries 7.0

**Comment by njNafir** [comment]
Okay, It's solved in 7.2

**Comment by venqics** [comment]
How is it solved, I am still getting the same error with django-countries 7.2

**Comment by IRunac** [comment]
Same, still getting same error with django-countries 7.5 while trying to upgrade to django 3.2.16.
`  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/hbx/bcore/apps/devops/management/commands/init_dbs.py", line 82, in handle
    call_command(
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/hbx/bcore/apps/devops/management/commands/load_fixtures.py", line 116, in handle
    self.remove_old_dbs(options)
  File "/home/ubuntu/hbx/bcore/apps/devops/management/commands/load_fixtures.py", line 111, in remove_old_dbs
    call_command("migrate")
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/migration.py", line 116, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 80, in state_forwards
    state.add_model(ModelState(
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 95, in add_model
    self.reload_model(app_label, model_name)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 156, in reload_model
    self._reload(related_models)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 189, in _reload
    self.apps.render_multiple(states_to_be_rendered)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 305, in render_multiple
    model.render(self)
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 565, in render
    body = {name: field.clone() for name, field in self.fields.items()}
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 565, in <dictcomp>
    body = {name: field.clone() for name, field in self.fields.items()}
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 512, in clone
    name, path, args, kwargs = self.deconstruct()
  File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1089, in deconstruct
    if self.db_collation:
AttributeError: 'CountryField' object has no attribute 'db_collation'`

**Comment by njNafir** [comment]
Using django version 3.2.4 and django-countries 7.2 resolved the issue at that time.
